//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_las_Finanzas_Personales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestión_de_Egresos
    {
        public int IdGestion_de_Egresos { get; set; }
        public string Tipos_de_Egresos { get; set; }
        public string Renglon_de_Egresos { get; set; }
        public string Tipo_de_Pago_por_Efecto { get; set; }
        public string Descripcion { get; set; }
        public int Estado { get; set; }
    
        public virtual Tipos_de_Egresos Tipos_de_Egresos1 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
