//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_las_Finanzas_Personales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestion_de_Ingresos
    {
        public int IdGestion_de_Ingresos { get; set; }
        public string Tipos_de_ingresos { get; set; }
        public string Descripcion { get; set; }
        public string Institucion_Empleador_Cliente { get; set; }
        public int Estado { get; set; }
    
        public virtual Tipos_de_Ingresos Tipos_de_Ingresos1 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
