//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_las_Finanzas_Personales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos_de_Ingresos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipos_de_Ingresos()
        {
            this.Gestion_de_Ingresos = new HashSet<Gestion_de_Ingresos>();
        }
    
        public string IdTipos_de_Ingresos { get; set; }
        public string Descripcion { get; set; }
        public int Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gestion_de_Ingresos> Gestion_de_Ingresos { get; set; }
    }
}
