//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_las_Finanzas_Personales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos_de_Egresos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipos_de_Egresos()
        {
            this.Gestión_de_Egresos = new HashSet<Gestión_de_Egresos>();
        }
    
        public string IdTipos_de_Egresos { get; set; }
        public string Descripcion { get; set; }
        public int Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gestión_de_Egresos> Gestión_de_Egresos { get; set; }
    }
}
