//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestión_de_las_Finanzas_Personales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int IdUsuarios { get; set; }
        public string Nombre { get; set; }
        public decimal Cedula { get; set; }
        public string Limite_Egresos { get; set; }
        public string Tipo_Persona { get; set; }
        public System.DateTime Fecha_Corte { get; set; }
        public int Estado { get; set; }
    
        public virtual Gestión_de_Egresos Gestión_de_Egresos { get; set; }
        public virtual Gestion_de_Ingresos Gestion_de_Ingresos { get; set; }
    }
}
